- name: "dnsmasq: DNS cache and contents server to reflect hosts.yml"
  hosts: dnsmasq/hosts
  roles:
    - role: dnsmasq/hosts
      when: inventory == 'staging'
  tags:
    - dnsmasq
    - dnsmasq/hosts

