- name: "OpenLDAP: Client and Server"
  hosts: openldap
  roles:
    - openldap
  tags:
    - openldap
    - openldap/client
    - openldap/server

- name: "OpenLDAP: DIT data in LDIF and provisioning"
  hosts: openldap/dit
  roles:
    - openldap/dit/base
    - role: openldap/dit/test
      when: inventory == 'staging'
  tags:
    - openldap
    - openldap/dit

- name: "OpenLDAP: Client"
  hosts: openldap/client
  roles:
    - openldap/client
  tags:
    - openldap
    - openldap/client

