- name: "OpenLDAP client and server"
  hosts: openldap
  roles:
    - openldap
  tags:
    - openldap
    - openldap-client
    - openldap-server

- name: "OpenLDAP client"
  hosts: openldap-client
  roles:
    - openldap/client
  tags:
    - openldap
    - openldap-client

