- name: "OpenLDAP client and server"
  hosts: openldap
  roles:
    - openldap
  tags:
    - openldap
    - openldap-client
    - openldap-server

- name: "OpenLDAP DIT"
  hosts: openldap-dit
  roles:
    - openldap/dit/base
    - role: openldap/dit/test
      when: inventory == 'staging'
  tags:
    - openldap
    - openldap-dit

- name: "OpenLDAP client"
  hosts: openldap-client
  roles:
    - openldap/client
  tags:
    - openldap
    - openldap-client

