openldap_vendor: os

openldap_server_port_manifest:
  - protocol: tcp
    port: 389
  - protocol: tcp
    port: 636
openldap_server_services:
  - ldapi:///
  - ldap:///
  - ldaps:///
openldap_server_options:
openldap_server_db_backend: bdb
openldap_server_bdb_cache_size: 64

openldap_master_id: -1

openldap_password_hash_name: CRYPT
openldap_password_crypt_salt_format: "$5$%.16s"

openldap_schemas:
  - core
  - cosine
  - nis
  - inetorgperson
  - ppolicy

openldap_master_rdn: cn=master
openldap_master_password: "{DISABLED}PASSWORD"
openldap_slave_rdn: cn=slave
openldap_slave_password: "{DISABLED}PASSWORD"
openldap_admin_rdn: cn=admin
openldap_admin_password: "{DISABLED}PASSWORD"

openldap_users_rdn: ou=Users
openldap_groups_rdn: ou=Groups
openldap_policies_rdn: ou=Policies

openldap_none_policy_rdn: cn=none
openldap_default_policy_rdn: cn=default
openldap_default_policy_password_attribute: userPassword
openldap_default_policy_password_lockout: true
openldap_default_policy_password_lockout_duration: 0
openldap_default_policy_password_max_failure: 10
openldap_default_policy_password_failure_count_interval: 0
openldap_default_policy_password_allow_user_change: true
openldap_default_policy_password_check_quality: 1
openldap_default_policy_password_in_history: 0
openldap_default_policy_password_min_length: 12

