openldap_vendor: os

openldap_client_server_uris:
#  - ldap://ldap1.example.jp/
#  - ldap://ldap2.example.jp/

openldap_server_port_manifest:
  - protocol: tcp
    port: 389
  - protocol: tcp
    port: 636
openldap_server_services:
  - ldapi:///
  - ldap:///
  - ldaps:///
openldap_server_options:
openldap_server_db_backend: bdb
openldap_server_bdb_cache_size: 64

openldap_tls_src_directory:
openldap_tls_ca_certificate_file_name:
openldap_tls_certificate_file_name:
openldap_tls_key_file_name:

openldap_master_id:

openldap_update_referral_uri:

openldap_password_hash_name: CRYPT
openldap_password_crypt_salt_format: "$5$%.16s"

openldap_schemas:
  - core
  - cosine
  - nis
  - inetorgperson
  - ppolicy

openldap_schema_files:
#  - site.schema
#  - extra.schema

openldap_attribute_options:
  - lang-
  - phonetic

openldap_master_rdn: cn=master
openldap_master_password: "{DISABLED}PASSWORD"

openldap_slave_rdn: cn=slave
openldap_slave_password: "{DISABLED}PASSWORD"
openldap_slave_masters:

openldap_admin_rdn: cn=admin
openldap_admin_password: "{DISABLED}PASSWORD"

openldap_users_rdn: ou=Users
openldap_groups_rdn: ou=Groups
openldap_policies_rdn: ou=Policies

openldap_none_policy_rdn: cn=none
openldap_default_policy_rdn: cn=default
openldap_default_policy_password_attribute: userPassword
openldap_default_policy_password_lockout: false
openldap_default_policy_password_lockout_duration: 0
openldap_default_policy_password_max_failure: 0
openldap_default_policy_password_failure_count_interval: 0
openldap_default_policy_password_allow_user_change: true
openldap_default_policy_password_check_quality: 0
openldap_default_policy_password_in_history: 0
openldap_default_policy_password_min_length: 0

openldap_test_users_rdn: ou=test
openldap_test_users_number: 1000
openldap_test_users_name_format: "u%04d"
openldap_test_users_password_format: "%04d"
openldap_test_users_uid_base: 100000
openldap_test_users_gid: 100
openldap_test_users_home_base: /home

openldap_test_groups_rdn: ou=test
openldap_test_groups_number: 10
openldap_test_groups_name_format: "g%04d"
openldap_test_groups_gid_base: 100000


