- include_vars: "{{item}}"
  with_first_found:
    - "vars/{{ansible_distribution |lower}}-{{ansible_distribution_version}}.yml"
    - "vars/{{ansible_distribution |lower}}-{{ansible_distribution_version |int}}.yml"
    - "vars/{{ansible_distribution |lower}}.yml"
    - "vars/{{ansible_os_family |lower}}-{{ansible_distribution_version}}.yml"
    - "vars/{{ansible_os_family |lower}}-{{ansible_distribution_version |int}}.yml"
    - "vars/{{ansible_os_family |lower}}.yml"

