- name: "Vendor package task"
  include: roles/vendor/{{package_vendor}}/package/tasks/{{ansible_pkg_mgr}}.yml
  when: package_vendor is defined and package_vendor not in [none, 'os']

- name: "Package manifest task"
  include: roles/package/manifest/tasks/{{ansible_pkg_mgr}}.yml
  when: package_manifest is not none

