hosts:
  ldap-master1:
    hostname: ldap-master1.example.jp
    memory: 512
    networks:
      - address: 10.255.1.11
        netmask: 255.255.255.0
  ldap-master2:
    hostname: ldap-master2.example.jp
    memory: 512
    networks:
      - address: 10.255.1.12
        netmask: 255.255.255.0
  ldap-slave1:
    hostname: ldap-slave1.example.jp
    memory: 512
    networks:
      - address: 10.255.1.21
        netmask: 255.255.255.0

