- name: "Base DIT data in LDIF file"
  template:
    src=base.ldif
    dest={{openldap_sysconf_dir}}/
    owner=root
    group={{openldap_server_group}}
    mode=0640
    backup=true
  become: true

- name: "Base DIT in LDAP server (prepare)"
  shell: |
    set -eu
    umask 0077
    : >{{openldap_sysconf_dir}}/base.current.ldif
    : >{{openldap_sysconf_dir}}/base.diff.ldif
  become: true
  changed_when: false

- name: "Base DIT in LDAP server"
  shell: |
    set -eu
    ret=0
    {{openldap_bin_dir}}/ldapsearch \
      -H ldapi:/// \
      -QY external \
      -b '{{item.base}}' \
      -s '{{item.scope}}' \
      -LLL \
      -o ldif-wrap=no \
      '{{item.filter if item.has_key("filter") else "(objectClass=*)"}}' \
      '*' \
      pwdPolicySubentry \
    >>{{openldap_sysconf_dir}}/base.current.ldif \
    || ret=$? \
    ;
    [ "$ret" -eq 0 ] || [ "$ret" -eq 32 ] || exit $ret
  with_items:
    - base: "{{openldap_suffix}}"
      scope: base
    - base: "{{openldap_suffix}}"
      scope: one
      filter: '(cn=*)'
    - base: "{{openldap_suffix}}"
      scope: sub
      filter: "(&(ou=*){{'(!('+openldap_test_users_rdn+'))' if openldap_test_users_rdn is defined else ''}}{{'(!('+openldap_test_groups_rdn+'))' if openldap_test_groups_rdn is defined else ''}})"
    - base: "{{openldap_default_policy_rdn}},{{openldap_policies_rdn}},{{openldap_suffix}}"
      scope: base
  become: true
  changed_when: false

- name: "Check if base.current.ldif has data"
  stat:
    path={{openldap_sysconf_dir}}/base.current.ldif
  become: true
  register: base_dit_current

- name: "Base DIT provisioning (full)"
  shell: |
    {{openldap_bin_dir}}/ldapadd \
      -H ldapi:/// \
      -QY external \
      -f {{openldap_sysconf_dir}}/base.ldif \
    ;
  become: true
  when: base_dit_current.stat.size == 0

- name: "Compare current base DIT in LDAP server and base.ldif"
  script: |
    files/ldifdiff.pl \
      --exclude-attrs=userPassword \
      {{openldap_sysconf_dir}}/base.current.ldif \
      {{openldap_sysconf_dir}}/base.ldif \
    >{{openldap_sysconf_dir}}/base.diff.ldif
  become: true
  when: base_dit_current.stat.size > 0
  changed_when: false

- name: "Check if base.diff.ldif has data"
  stat:
    path={{openldap_sysconf_dir}}/base.diff.ldif
  become: true
  register: base_dit_diff

- name: "Base DIT provisioning (incremental)"
  shell: |
    awk '
      {print}
      /^dn:/ {dn=$0}
      /^changetype: add$/ {
        system("sed -n \"/^"dn"/,/^$/ { /^userPassword:/p }\" {{openldap_sysconf_dir}}/base.ldif")
      }' \
      {{openldap_sysconf_dir}}/base.diff.ldif \
    |{{openldap_bin_dir}}/ldapmodify \
      -H ldapi:/// \
      -QY external \
    ;
  become: true
  when: base_dit_current.stat.size > 0 and base_dit_diff.stat.size > 0

