- name: "Package manifest"
  include: roles/package/manifest/tasks/main.yml
  vars:
    package_manifest: "{{openldap_server_package_manifest}}"
    package_vendor: "{{openldap_vendor if openldap_vendor is defined else none}}"

- name: "slapd.conf"
  template:
    src=slapd.conf.j2
    dest={{openldap_dirs_sysconf}}/slapd.conf
    owner=root
    group=ldap
    mode=0640
    backup=true
  become: true
  notify: slapd reload

- name: "slapd.d (remove to disable slapd-config(5))"
  file:
    path={{openldap_dirs_sysconf}}/slapd.d
    state=absent
  become: true

- name: "slapd default file"
  template:
    src=slapd.default.j2
    dest={{openldap_server_default_file}}
    owner=root
    group=root
    mode=0644
    backup=true
  become: true
  when: openldap_server_default_file is not none
  notify: slapd reload

- name: "Schema files"
  copy:
    src={{item}}
    dest={{openldap_dirs_sysconf}}/schema/
    mode=0644
    owner=root
    group=root
  with_items: "{{openldap_schema_files}}"
  become: true
  when: openldap_schema_files is not none

- name: "TLS key and certificate directory"
  file:
    path={{item.path}}
    state=directory
    mode={{'0%o' |format(item.mode)}}
    owner=root
    group=ldap
  with_items:
    - path: "{{openldap_dirs_sysconf}}/private"
      mode: 0750
    - path: "{{openldap_dirs_sysconf}}/certs"
      mode: 0755
  become: true

- name: "TLS CA certificate file"
  copy:
    src={{openldap_tls_ca_certificate_file}}
    dest={{openldap_dirs_sysconf}}/certs/
    mode=0444
    owner=root
    group=ldap
  become: true
  when: openldap_tls_ca_certificate_file is defined
  notify: slapd reload

- name: "TLS certificate file"
  copy:
    src={{openldap_tls_certificate_file}}
    dest={{openldap_dirs_sysconf}}/certs/
    mode=0444
    owner=root
    group=ldap
  become: true
  when: openldap_tls_certificate_file is defined
  notify: slapd reload

- name: "TLS key file"
  copy:
    src={{openldap_tls_key_file}}
    dest={{openldap_dirs_sysconf}}/private/
    mode=0440
    owner=root
    group=ldap
  become: true
  when: openldap_tls_key_file is defined
  notify: slapd reload

- name: "DB directry"
  file:
    path={{openldap_dirs_db}}
    state=directory
    owner=ldap
    group=ldap
    mode=700
  become: true
  register: db_dir

- name: "SELinux security context on DB directry"
  shell: |
    type /sbin/restorecon >/dev/null 2>&1 || exit 0
    /sbin/restorecon "{{openldap_dirs_db}}"
  when: db_dir.changed

- name: "slapd service"
  service:
    name={{openldap_server_service_name}}
    state=started
    enabled=true
  become: true

