openldap_server_package_manifest:
  - name: openldap-servers
openldap_client_package_manifest:
  - name: openldap-clients

openldap_server_service_name: slapd
openldap_server_default_file: /etc/sysconfig/ldap
openldap_server_user: ldap
openldap_server_group: ldap

openldap_sysconf_dir: /etc/openldap
openldap_bin_dir: /usr/bin
openldap_sbin_dir: /usr/sbin
openldap_db_dir: /var/lib/ldap
openldap_run_dir: /var/run/openldap


