- include: roles/package/manifest/tasks/main.yml
  vars:
    package_manifest: "{{dnsmasq_package_manifest}}"

- name: "dnsmasq.conf"
  copy:
    src: dnsmasq.conf
    dest: "{{dnsmasq_sysconf_dir}}/dnsmasq.conf"
    mode: 0755
    owner: root
    group: root
    backup: true
  become: true
  notify: dnsmasq reload

- name: "dnsmasq.hosts"
  template:
    src: dnsmasq.hosts
    dest: "{{dnsmasq_sysconf_dir}}/"
    mode: 0755
    owner: root
    group: root
    backup: true
  become: true
  notify: dnsmasq reload

- name: "OS, distribution, version specific tasks"
  include: "{{item}}"
  with_first_found:
    - files:
        - "{{ansible_distribution |lower}}-{{ansible_distribution_version}}.yml"
        - "{{ansible_distribution |lower}}-{{ansible_distribution_version |int}}.yml"
        - "{{ansible_distribution |lower}}.yml"
        - "{{ansible_os_family |lower}}-{{ansible_distribution_version}}.yml"
        - "{{ansible_os_family |lower}}-{{ansible_distribution_version |int}}.yml"
        - "{{ansible_os_family |lower}}.yml"

## FIXME: nmcli con mod {{if}} ipv4.dns 127.0.0.1
- name: "resolv.conf"
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0755
    owner: root
    group: root
    backup: true
  become: true

- name: "dnsmasq.resolv.conf"
  stat:
    path: "{{dnsmasq_sysconf_dir}}/dnsmasq.resolv.conf"
  register: resolv_dnsmasq_conf
  changed_when: not resolv_dnsmasq_conf.stat.exists
  notify: network reload

- name: "dnsmasq service"
  service:
    name: "{{item}}"
    state: running
    enabled: true
  with_items:
    - dnsmasq
  become: true

- meta: flush_handlers

